apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs-app
  labels:
    app: sample-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-nodejs-app
  template:
    metadata:
      labels:
        app: sample-nodejs-app
    spec:
      containers:
        - name: sample-nodejs-app
          image: venkatesh1409/sample-nodejs-app:1.0.0
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
