apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs-app
spec:
  replicas: 2 # Number of replicas, managed pods
  selector:
    matchLabels:
      app: sample-nodejs-app
      workload: dev
  template:
    metadata:
      labels:
        app: sample-nodejs-app
        workload: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: sample-nodejs-container
          image: venkatesh1409/sample-nodejs-app:0.0.1
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: "64Mi"
              cpu: "1"
          
 