apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-nodejs-app
  template:
    metadata:
      labels:
        app: sample-nodejs-app
    spec:
      containers:
      - name: sample-nodejs-container
        image: your-dockerhub-username/sample-nodejs-app:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: sample-nodejs-configmap
