apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-nodejs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sample-nodejs.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-nodejs-app
            port:
              number: 80
