#service type 4, ClusterIP, nodeport, loadbalancer, externalname

apiVersion: v1
kind: Service
metadata:
  name: sample-nodejs-service
spec:
  selector:
    app: sample-nodejs-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
