pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "venkatesh1409/sample-nodejs-app"
        DOCKER_TAG   = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/iam-venkateshwarlu/Docker-example.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('app') {
                        dockerImage = docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}")
                    }
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                script {
                    sh "trivy image --exit-code 0 --severity HIGH,CRITICAL ${DOCKER_IMAGE}:${DOCKER_TAG} || true"
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        // stage('Clean Up') {
        //     steps {
        //         script {
        //             sh "docker rmi ${DOCKER_IMAGE}:${DOCKER_TAG} || true"
        //             sh "docker rmi ${DOCKER_IMAGE}:latest || true"
        //         }
        //     }
        // }
    }
}
