pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "venkatesh1409/sample-nodejs-app"
        DOCKER_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/iam-venkateshwarlu/Docker-example.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('app') {
                    // Assuming the Node.js app has a package.json file
                    sh 'npm install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", "app/")
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh 'trivy image --exit-code 1 --severity HIGH,CRITICAL $DOCKER_IMAGE:$DOCKER_TAG || true'
            }
        }

        stage('Push Docker Image') {
            steps {
                 script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        docker.image("venkatesh1409/sample-nodejs-app:${BUILD_NUMBER}").push()
                    }
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                 script {
            sh '''
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
            '''
                 }
            }
        }
    }
}
